apiVersion: v1
kind: Service
metadata: 
  name: hello-world
  labels: 
    app: hello-world
    
spec:
  type: Loadbalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector: 
    app: hello-world
    
---
apiVersion: app/v1
kind: Deployement
metadata: 
  name: hello-world
  labels:
    app: hello-world
  
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: hello-world
  template: 
    metadata:
      labels:
        app: hello-world
    spec:
      containers: 
      - name: springboot
        image: latest
        imagePullPolicy: Always
        ports: 
        - conatainerPort: 8080
        
