apiVersion: v1
kind: Service
metadata: 
  name: web-app
  labels: 
    app: web-app
    
spec:
  type: Nodeport
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector: 
    app: web-app
    
---
apiVersion: app/v1
kind: Deployement
metadata: 
  name: web-app
    labels: 
      app: web-app
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: web-app
  template: 
    metadata:
      labels:
        app: web-app
    spec:
      containers: 
      - name: springboot
        image: latest
        imagePullPolicy: Always
        ports: 
        - conatainerPort: 8080
